name: Update Standings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-standings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Upgrade to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Upgrade to the latest version
        with:
          node-version: 20 # Specify Node.js 20 explicitly for compatibility

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scraper.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add standings.json
          git commit -m "Update standings [skip ci]" || echo "No changes to commit"
          git push
